encrypt:
 key-store:
    location: Aoserver.jks
    password: Ase\rV5Er@12
    alias: aoplatformkey
    secret: Ase\rV5Er@12@secret123
   
spring:
   datasource:   
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/ao-db-content
        name:
        username: postgres
        password: '{cipher}AQCCb0upSWorIo9NMeZvNV0kJm2AgpPzJaXupBXMgcdt4feG5fb2kwp4qjePMnyDhLTV+NLp1f0gLFOKn72LnYEM0HbVxIhM9odLWRzqdRYbFVi98q+sdPSwrXTbnZEPzR3jTK3sm51GhBjbvYO37u4uNdZ6Ey1AcQoOX9dMMiClo+3bfKtTMwXUt2Qod5y2RT66P3hIb370kIJemm788m2CmdwAtcopKldZh0ASqLmyBwNnvuH8u2IFheJ1tHpzdETX7j38ajoSXXBtr0Gakk32NFExfWVpXW5QMTqM4kgCCKcXaWR1YfHRyM/rqasP55nVwqLAFWQlQFxd1RjkZ6XrhoZMAEn9d2mvridHmTfe3w8wT3L1NezfpamW+z6JEng='        
        dbcp2:
           max-idle: 2
           min-idle: 0
           max-conn-lifetime-millis: 600000
           initial-size: 5
           max-total: 10
           test-while-idle: false
           test-on-borrow: false
           additionalProperties:        
server:
  port: 8090
  #ssl:
    #key-store-type: PKCS12
    #key-store: classpath:keystore.p12
    #key-store-password: water123
    #key-alias: tomcat  
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
